
# metadata
element-match-dev:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: augment
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_TEST
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST

    - pip3 install -r element-matcher/requirements.txt
    #- python3 keyword-matcher/get_thesaurus.py
    - python3 element-matcher/match.py
  rules:
    - if: $PROJECT != "ELMATCH"
      when: never
    - if: $CI_COMMIT_REF_NAME == "develop"


# metadata
element-match-prod:
  image: harbor.containers.wurnet.nl/proxy-cache/library/python:3.10.8-slim-buster
  stage: augment
  script:
    - export POSTGRES_HOST=$POSTGRES_HOST_TEST
    - export POSTGRES_PORT=$POSTGRES_PORT_TEST
    - export POSTGRES_DB=$POSTGRES_DB_PROD
    - export POSTGRES_USER=$POSTGRES_USER_TEST
    - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD_TEST
    
    - pip3 install -r element-matcher/requirements.txt
    #- python3 keyword-matcher/get_thesaurus.py
    - python3 element-matcher/match.py
  rules:
    - if: $PROJECT != "ELMATCH"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"

